3.49 access control DONE
patriktao/Next-MemberFlow pull request #4
Opened 2023-04-05 21:42 UTC by iohnS

2023-04-05 23:01 UTC, patriktao requested changes
Får fel när jag ska använda cloud funktionerna, finns också lite små kommentarer, men det mesta ser bra ut!

2023-04-05 23:01 UTC, patriktao commented on components/admin/AddAdminModal.tsx
Använd FormModal under UI_components istället så minskar vi risken att behöva ändra varje modal om vi t.ex. behöver justera en gemensam variabel.

2023-04-05 23:01 UTC, patriktao commented on components/tables/AdminTable/AdminTable.tsx
Ser bra ut! Vi kan fixa designen senare

2023-04-05 23:01 UTC, patriktao commented on functions/index.js
Föreslår att vi lägger dessa funktioner i en adminAPI-fil i samma mapp, som sedan importeras in i index.js filen. Vi vill gärna hålla index.js clean om vi i framtiden användar oss av flera cloud funktioner med olika syften 

Får dessutom en 
`POST http://localhost:5001/memberflow-api/europe-central2/removeAdmin net::ERR_CONNECTION_REFUSED`
`FirebaseError: internal`
när jag testar funktionerna

2023-04-05 23:01 UTC, patriktao commented on pages/settings.tsx
Behöver inte ändras just nu

2023-04-06 07:36 UTC, iohnS commented on functions/index.js
Funktionerna kräver just nu att man använder emulatorn: "firebase emulators:start --only functions"

2023-04-07 17:01 UTC, patriktao approved these changes

2023-04-07 17:01 UTC, merged